eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        serviceUrl:
            defaultZone: http://localhost:8000/eureka/
server:
    port: 8000
spring:
    application:
        name: spring-cloud-eureka
