eureka:
    client:
        serviceUrl:
            defaultZone: http://peer2:8001/eureka/
    instance:
        hostname: peer1
server:
    port: 8000
spring:
    application:
        name: spring-cloud-eureka
