eureka:
    client:
        serviceUrl:
            defaultZone: http://peer1:8000/eureka/
    instance:
        hostname: peer2
server:
    port: 8001
spring:
    application:
        name: spring-cloud-eureka
